Add file existence check to analyse script

diff --git a/analyse b/analyse
--- a/analyse
+++ b/analyse
@@ -8,3 +8,10 @@ then
     echo "ERROR: No input CSV file provided"
     exit 1
 fi
+
+# Check file exists
+if test ! -f "$file"
+then
+    echo "ERROR: Input file not found in the current directory"
+    exit 1
+fi
