Add empty file check for clean script

diff --git a/clean b/clean
--- a/clean
+++ b/clean
@@ -9,6 +9,13 @@ then
     exit 1
 fi
 
+# Check that the input file is not empty
+if test ! -s "$file"
+then
+    echo "ERROR: Empty file provided"
+    exit 1
+fi
+
 # Check that the input file has a .csv extension
 if ! echo "$file" | grep '\.csv$' > /dev/null
 then
