Fix argument check to accept one input file

diff --git a/clean b/clean
--- a/clean
+++ b/clean
@@ -14,3 +14,9 @@ then
     echo "Usage: ./clean <input_file> <output_file>" >&2
     exit 1
 fi
+# Must have exactly one argument
+if test "$#" -ne 1
+then
+    echo "ERROR: No input CSV file provided"
+    exit 1
+fi
